
create or replace type Numero_de_Cuenta as object(
numero_deposito varchar(32),
numero_retiro varchar(32)
);
/
create or replace type Descripcion as object(
nombre varchar(32),
descripcion varchar(32),
fecha_incorporacion date
);
/
create or replace type Detalle as object(
cantidad int,
fecha_realizacion date,
tasa_de_canje int
);
/
create or replace type Condicion as object(
precio_limite int,
fecha_limite date,
tipo varchar(32)
);
/
create or replace type Pais as object(
nombre varchar(32),
codigo_iso varchar(32)
);
/
create or replace type Telefono as VARRAY(2) of Int;
/
create or replace type Pasaporte as VARRAY(3) of Int;
/
create or replace type Fundadores as VARRAY(2) of VARCHAR(40);
/

create or replace type Pago_Tarjeta as Object(
tipo varchar(20),
numero int,
tarjetahabiente varchar(60),
fecha_vencimiento date
);
/
create or replace type Tarjeta as table of Pago_Tarjeta;
/ 
create table Direccion (
dir_codigo numeric GENERATED by default as IDENTITY primary key,
dir_calle varchar(20),
dir_avenida varchar(20),
dir_edificio varchar(20),
dir_ciudad varchar(20),
dir_pais Pais not null
);
 /
create table Usuario (
usu_codigo numeric GENERATED by default as IDENTITY primary key,
usu_nombre varchar(20) not null,
usu_apellido varchar(20) not null,
usu_clave varchar(20),
usu_foto_pasaporte blob,
usu_pasaporte Pasaporte,
usu_telefono Telefono,
usu_tarjeta Tarjeta,
fk_dir_codigo int REFERENCES Direccion(dir_codigo))
nested table usu_tarjeta store as tarjeta_ta;
/

create table Moneda(
mon_codigo numeric GENERATED by default as IDENTITY primary key,
mon_descripcion Descripcion not null,
mon_valor float not null,
mon_logo blob,
mon_pais_origen Pais,
mon_fundadores Fundadores
);
/

create table Billetera (
bil_codigo numeric GENERATED by default as IDENTITY primary key,
bil_cantidad int  not null, 
bil_numero Numero_de_Cuenta not null,
fk_usu_codigo int REFERENCES Usuario(usu_codigo),
fk_mon_codigo int REFERENCES Moneda(mon_codigo)
);
/

create table Orden_Limit(
ord_lim_codigo numeric GENERATED by default as IDENTITY primary key,
ord_lim_detalle Detalle  not null,
ord_lim_fecha_inicio date  not null,
ord_lim_condicion Condicion  not null,
fk_usu_codigo int REFERENCES Usuario(usu_codigo),
fk_mon_ofrecida_codigo int REFERENCES Moneda(mon_codigo),
fk_mon_solicitada_codigo int REFERENCES Moneda(mon_codigo)
);
/

create table Orden_Market(
ord_mar_codigo numeric GENERATED by default as IDENTITY primary key,
ord_mar_detalle Detalle  not null,
ord_mar_fecha_inicio date  not null,
ord_mar_precio_actual_favorable int  not null,
fk_usu_codigo int REFERENCES Usuario(usu_codigo),
fk_mon_ofrecida_codigo int REFERENCES Moneda(mon_codigo),
fk_mon_solicitada_codigo int REFERENCES Moneda(mon_codigo)
);
/

create table Mercado(
mer_codigo numeric GENERATED by default as IDENTITY primary key,
mer_capacicidad int  not null,
mer_descripcion Descripcion  not null
);
/


create table Evento(
eve_codigo numeric GENERATED by default as IDENTITY primary key,
eve_descripcion Descripcion not null,
eve_fecha_fin date not null,
eve_tipo_efecto varchar(10) not null,
fk_mon_codigo int REFERENCES Moneda(mon_codigo)
);
/

create table Mer_Mon(
mer_mon_codigo numeric GENERATED by default as IDENTITY primary key,
mer_mon_principal varchar(3) not null,
fk_mer_codigo int REFERENCES Mercado(mer_codigo),
fk_mon_codigo int REFERENCES Moneda(mon_codigo) 
);
/
 
create table Precio( 
pre_codigo numeric GENERATED by default as IDENTITY primary key,
pre_fecha date not null,
pre_monto int,
fk_mon_ofrecida_codigo REFERENCES Moneda(mon_codigo),
fk_mon_solicitada_codigo REFERENCES Moneda(mon_codigo)
);
/

create table Transaccion(
tra_codigo numeric GENERATED by default as IDENTITY primary key,
tra_detalle Detalle not null,
tra_numeros_de_cuenta Numero_de_Cuenta not null,
fk_mon_ofrecida_codigo int REFERENCES Moneda(mon_codigo),  --Mp
fk_mon_solicitada_codigo int REFERENCES Moneda(mon_codigo) -- Mp
);
/

create table Ord_Tra(
ord_tra_codigo numeric GENERATED by default as IDENTITY primary key,
fk_tra_codigo int not null,
fk_ord_lim_codigo int REFERENCES Orden_Limit(ord_lim_codigo),
fk_ord_mar_codigo int REFERENCES Orden_Market(ord_mar_codigo)
);
