--Prediccion Medias Moviles 
drop table Pronostico_Medias;
create table Pronostico_Medias (id number generated by default as identity,valor_real float, prediccion float, error_cuadrado float);

--ESTA funcion me devuelve el % de error, me devuelve el MSN NADA MAS 
create or replace function Func_promedio_medias_I (num_transacciones IN number,mon_ofrecida_codigo IN NUMBER, mon_solicitada_codigo IN NUMBER)
return float 
is
errores float;
contador int;
contador_id int;
errores_total float;

x1 float;
x2 float;
x3 float;

begin 
contador_id:=0;
  --Insert los valores de la primera columna (Valor_REAL)
  delete from Pronostico_Medias;
  for i in((Select val from(
  select t.tra_detalle.tasa_de_canje as val from Transaccion t where t.fk_mon_solicitada_codigo = mon_solicitada_codigo and t.fk_mon_ofrecida_codigo = mon_ofrecida_codigo 
  order by t.tra_detalle.fecha_realizacion desc)
  where ROWNUM <= num_transacciones))loop 
  insert into Pronostico_Medias(valor_real) values(i.val);
  end loop;

  --Insert los valores de la segunda columna (Prediccion)
  for i in (select * from Pronostico_Medias pm order by id desc ) loop --Ordeno la primera columna 
  if(contador_id>2) then 
  select valor_real into x1 from Pronostico_Medias where id=i.id+1;
  select valor_real into x2 from Pronostico_Medias where id= i.id+2;
  select valor_real into x3 from Pronostico_Medias where id= i.id+3;
  
  Update Pronostico_Medias set prediccion = (((x1+x2+x3)/3)) where id = i.id;
  Update Pronostico_Medias set error_cuadrado = POWER ((abs(valor_real - prediccion)),2) where id = i.id;
  end if;
  contador_id:=contador_id + 1;
  end loop;
  
  --sumatoria de los errores cuadrados en errores
  select sum (p.error_cuadrado) 
  into errores 
  from Pronostico_Medias p;
  --contador de errores totales
  select count (*)
  into contador
  from Pronostico_Medias;
  
  errores_total:=errores/(contador-3);
  return errores_total;
end Func_promedio_medias_I;
  --FIN DE LA PRIMERA ---------------------------------------------------------------------------------------------------------------------------
  
  
  --ESTA FUNCION me devuelve la prediccion 
  create or replace function Func_promedio_medias_II (num_transacciones IN number,mon_ofrecida_codigo IN NUMBER, mon_solicitada_codigo IN NUMBER)
return float 
is
sumatoria float;
prediccion_verdadera float;
begin 
  Select AVG(valor_real) 
  into sumatoria
  from(
  Select valor_real from (select valor_real from Pronostico_Medias order by id asc) where rownum<=3);
 return sumatoria;
 end Func_promedio_medias_II;
 

 --FIN DE LA SEGUNDA ----------------------------------------------------------------------------------------------------------------------------
  --Este procedure me imprime las 2 funciones de arriba
  create or replace Procedure Pronostico_Medias_Imprimir(num_transacciones IN number,mon_ofrecida_codigo IN NUMBER, mon_solicitada_codigo IN NUMBER) 
   is
  begin 
    dbms_output.put_line('El MSN (% de error) es: ' || Func_promedio_medias_I(num_transacciones,mon_ofrecida_codigo,mon_solicitada_codigo) || 
    ' La estimacion futura de la moneda es: ' || Func_promedio_medias_II(num_transacciones,mon_ofrecida_codigo,mon_solicitada_codigo) );
        
  end;
  select * from Pronostico_Medias;
  call Pronostico_Medias_Imprimir(10,7,1);
